SCREEN_HEIGHT = 540
SCREEN_WIDTH = 960
BOARD_SIZE = 8
TILE_SIZE = 50
FRAME_SIZE = (SCREEN_HEIGHT - TILE_SIZE * BOARD_SIZE) // 2
BOARD_WIDTH = BOARD_SIZE * TILE_SIZE

BOARD_POS_X = SCREEN_WIDTH // 2 - SCREEN_HEIGHT // 2 + FRAME_SIZE
BOARD_POS_Y = FRAME_SIZE
