SCREEN_HEIGHT = 1080
SCREEN_WIDTH = 1920
BOARD_SIZE = 8
FRAME_SIZE = 40
TILE_SIZE = (SCREEN_HEIGHT - 2 * FRAME_SIZE) // BOARD_SIZE

BOARD_POS_X = SCREEN_WIDTH // 2 - SCREEN_HEIGHT // 2
BOARD_POS_Y = 0